<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>	
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Anime List</title>
<link rel="stylesheet"
	href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
	integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
	crossorigin="anonymous">
<style>
/* Your existing CSS styles */
.anime-list {
	max-width: 800px;
	margin: 0 auto;
	padding: 20px;
	background-color: rgba(255, 255, 255, 0.9);
	border-radius: 10px;
	box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
}

.anime-list h2 {
	font-size: 24px;
	margin-bottom: 20px;
	color: #333;
	text-align: center;
}

table {
	width: 100%;
	border-collapse: collapse;
}

th, td {
	padding: 10px;
	text-align: left;
	border-bottom: 1px solid #ddd;
}

th {
	background-color: #f2f2f2;
	font-weight: bold;
}
input{
	margin:10px;
}
h3{
	background-color:#79d2a6;
}
a{
	margin-left:12px;
}

</style>
</head>
<body>
	<div class="anime-list">
		<h2>Anime List</h2>
		<a href="<%=request.getContextPath()%>/list" class="nav-link">Refresh List</a>
		<c:if test="${not empty requestScope.NOTIFICATION }">
			<h3 class="alert alert-success" role="alert"><%=request.getAttribute("NOTIFICATION") %></h3>
		</c:if>
		<form action="update" method="post">
			<table>
				<tr>
					<th>Anime Name</th>
					<th>Status</th>
				</tr>
				<!-- The following part will be dynamically generated by the backend -->
				<c:forEach items="${animelist}" var="anime">
				
					<tr>
						<td><input type="text" name="animeName" value="${anime.animeName}" readonly></td>
						<td> 
							<input type="checkbox" name="watched_${anime.animeName}" ${anime.watched?"checked":"" } />Watched
							<input type="checkbox" name="watchLater_${anime.animeName}" ${anime.watchLater?"checked":"" } />Watch Later
							<input type="checkbox" name="completed_${anime.animeName }" ${anime.completed?"checked":"" } />Completed
							<a class="btn btn-danger btn-sm" href="delete?id=<c:out value='${anime.id }'/>">-</a>
						</td>
					</tr>
				</c:forEach>
				<!-- End of dynamic content -->
			</table>
			<button class="btn btn-primary" type="submit">Update Status</button>
			<a class="btn btn-primary" href="<%=request.getContextPath()%>/form.jsp">Add Anime</a>
		</form>
	</div>
</body>
</html>
